// colors.tsx

type Colors = {
  white: string;
  black: string;
  slate200: string;
  slate100: string;
  grey100: string;
  grey500: string;
  grey600: string;
  fontColor: string;
  greyLight: string;
  grey: string;
  greyDark: string;
  greyDarkPlus: string;
  greyIconPlus: string;
  greyTextColor: string;
  greyTextDarkColor: string;
  primaryColor: string;
  primaryColorNew: string;
  primaryColorDark: string;
  primaryColorDarkNew: string;
  primaryColorLight: string;
  primaryColorLight2: string;
  secondaryColor: string;
  secondaryColorDark: string;
  secondaryColorLight: string;
  dark: string;
  dark100: string;
  dark600: string;
  default: string;
  defaultLight: string;
  defaultText: string;
  disabled: string;
  disabledText: string;
  background: string;
  blackaccentColor: string;
  accentColorLight: string;
  accentColorMedium: string;
  textPrimaryColor: string;
  textSecondryColor: string;
  accentColor: string;
  green: string;
  red: string;
  atulsiaColor: string;
  buyerPrimary: string;
  buyerPrimarydark: string;
  buyerPrimaryLight: string;
};

const COLORS: Colors = {
  white: '#fff',
  black: '#000',
  slate200: '#E2E8F0',
  slate100: '#F1F5F9',
  grey100: '#F3F4F6',
  grey500: '#6B7280',
  grey600: '#4B5563',
  fontColor: '#1F2937',
  greyLight: '#f4f2f2',
  grey: '#dfdfdf',
  greyDark: '#c3c3c3',
  greyDarkPlus: '#bababa',
  greyIconPlus: '#9f9a9a',
  greyTextColor: '#8d8d8d',
  greyTextDarkColor: '#817f7f',
  primaryColor: '#2993b9',
  primaryColorNew: '#1B263B',
  primaryColorDark: '#184D74',
  primaryColorDarkNew: '#111B2C',
  primaryColorLight: '#f0fbff',
  primaryColorLight2: '#BCD0DF',
  secondaryColor: '#FFBA08',
  secondaryColorDark: '#CC9506',
  secondaryColorLight: '#FFF1CE',
  dark: '#2B2D42',
  dark100: '#D5D5D9',
  dark600: '#222435',
  default: '#D1D5DB',
  defaultLight: '#F3F4F6',
  defaultText: '#1F2937',
  disabled: '#D1D5DB',
  disabledText: '#4B5563',
  background: '#F1F5F9',
  blackaccentColor: '#0d3fc5',
  accentColorLight: '#f6c27e',
  accentColorMedium: '#33546d',
  textPrimaryColor: '#000000',
  textSecondryColor: '#68696b',
  accentColor: '#1E6091',
  green: '#0ed00e',
  red: 'red',
  atulsiaColor: '#1bbc9c',
  buyerPrimary: '#cb4154',
  buyerPrimarydark: '#be3447',
  buyerPrimaryLight: '#db7d8a',
};

export default COLORS;
